#!/usr/bin/env bash
# build-ollama-image.sh — build a custom Ollama image with OLLAMA_MODEL pre-baked,
# then push to ACR. Idempotent.
#
# Prereqs in /tmp/deploy-vars.sh: ACR_NAME, OLLAMA_MODEL.
set -euo pipefail

: "${ACR_NAME:?}"
: "${OLLAMA_MODEL:?}"

# Baked Ollama images REQUIRE local Docker Desktop.
# ACR Build cannot run `ollama serve` in RUN instructions — the daemon silently
# fails, the pull hangs, and the image never appears in ACR.
if ! docker info >/dev/null 2>&1; then
  echo "ERROR: Docker is not running. Baked Ollama images require local Docker Desktop." >&2
  echo "       'az acr build' CANNOT build baked Ollama images (ollama serve fails inside ACR Build)." >&2
  echo "       Either start Docker Desktop, or switch to runtime-pull strategy:" >&2
  echo "         export OLLAMA_IMAGE_STRATEGY=runtime-pull" >&2
  echo "         export OLLAMA_IMAGE=docker.io/ollama/ollama:latest" >&2
  exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$SCRIPT_DIR/../../../.." && pwd )"
BUILD_DIR="$REPO_ROOT/sidecar/dev/ollama"

mkdir -p "$BUILD_DIR"
cat > "$BUILD_DIR/Dockerfile" <<DOCKERFILE
# Auto-generated by build-ollama-image.sh
FROM ollama/ollama:latest
ENV OLLAMA_HOST=0.0.0.0:11434

# Pre-pull the model so replicas start with weights on disk.
# This takes 1-5 minutes depending on model size.
RUN ollama serve & \\
    sleep 5 && \\
    ollama pull ${OLLAMA_MODEL} && \\
    pkill ollama || true

EXPOSE 11434
ENTRYPOINT ["ollama", "serve"]
DOCKERFILE

# Tag incorporates the model name for traceability.
TAG=$(echo "$OLLAMA_MODEL" | tr ':.' '-')
IMAGE="${ACR_NAME}.azurecr.io/agent-id-dev/ollama:${TAG}"

echo "Building $IMAGE (baked model: $OLLAMA_MODEL)..."
az acr login --name "$ACR_NAME"
docker buildx build --platform linux/amd64 -t "$IMAGE" --push "$BUILD_DIR"

echo "Pushed: $IMAGE"
echo "export OLLAMA_IMAGE=\"$IMAGE\"" >> "${VARS_FILE:-/tmp/deploy-vars.sh}"
